/*
 * File: app/view/HNGrid.js
 *
 * This file was generated by Sencha Architect version 4.1.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('NewsApp.view.HNGrid', {
    extend: 'Ext.grid.Grid',
    alias: 'widget.hngrid',

    requires: [
        'NewsApp.view.HNGridViewModel',
        'Ext.grid.column.Column'
    ],

    viewModel: {
        type: 'hngrid'
    },
    height: '100%',
    width: '100%',
    store: 'HNStore',

    columns: [
        {
            xtype: 'gridcolumn',
            renderer: function(value, record, dataIndex, cell, column) {

                return '<a target="_blank" href="'+record.get('url') + '">' + value + '</a>';
            },
            flex: '1',
            cell: {
                encodeHtml: false
            },
            dataIndex: 'title',
            text: 'Title'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'author',
            text: 'Author'
        },
        {
            xtype: 'gridcolumn',
            dataIndex: 'points',
            text: 'Points'
        }
    ]

});